services:
  node1:
    image: atlassian/jira-software
    ports:
     - 9090:8080
    volumes:
      - ./jira-home-node1:/var/atlassian/application-data/jira:Z
      - ./jira-shared-home:/var/atlassian/jira-shared-home:z
    environment:
      CATALINA_OPTS: -Datlassian.cluster.scale=true -DjvmRoute=node1 -Datlassian.dev.mode=true
      DB_HOST: infrastructure-postgres
      DB_PORT: 5432
      DB_USER: ${USER}
      DB_PASSWORD:
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - bugcrowd_infra
networks:
  bugcrowd_infra:
    external: true
